Update jen-op-3366927u

diff --git a/jen-op-3366927u b/jen-op-3366927u
--- a/jen-op-3366927u
+++ b/jen-op-3366927u
@@ -42,27 +42,29 @@ pipeline {
           stage('Op-3366927u-S3') {
 	          steps {
 				// proceed or rollback
-				v2 = input ( 
-                	message: 'Action',
-                    parameters: [choice(name:'',choices: ['Proceed to Roll out to Prod server', 'Roll back QA server'])]
-					)
-				// if proceed			
-				if (v2 == 'Proceed to Roll out to Prod server'){
- 					echo 'Op-3366927u-S3: Proceed to roll out to Prod server'
-					}
-				else if (v2 == 'Roll back QA server') {
-					// if rollback, then
-					// execute rollback of qa web svr by using qa-bkup-image
-					// remove qa svr container
-					sh 'docker rm -f 3366927u-qa-svr || true'
-					// run another qa-svr from qa backup image
-					sh 'docker run -d -p 33200:80 --network customnetwork -h 3366927u-qa-svr.localdomain --name 3366927u-qa-svr  --add-host=sddo-vm.localdomain:172.20.113.173 --ip=192.168.100.110 --mount source=qa-volume,target=/mnt/qa-volume qa-bkup-image /usr/sbin/sshd -D'  
-					echo 'Op-3366927u-S3: QA server fails after update and is rolled back'
-					// then use error('aborting') to abort rest of steps
-					
-	                error('aborting')
-
-					}
+				script {
+					v2 = input ( 
+	                	message: 'Action',
+	                    parameters: [choice(name:'',choices: ['Proceed to Roll out to Prod server', 'Roll back QA server'])]
+						)
+					// if proceed			
+					if (v2 == 'Proceed to Roll out to Prod server'){
+	 					echo 'Op-3366927u-S3: Proceed to roll out to Prod server'
+						}
+					else if (v2 == 'Roll back QA server') {
+						// if rollback, then
+						// execute rollback of qa web svr by using qa-bkup-image
+						// remove qa svr container
+						sh 'docker rm -f 3366927u-qa-svr || true'
+						// run another qa-svr from qa backup image
+						sh 'docker run -d -p 33200:80 --network customnetwork -h 3366927u-qa-svr.localdomain --name 3366927u-qa-svr  --add-host=sddo-vm.localdomain:172.20.113.173 --ip=192.168.100.110 --mount source=qa-volume,target=/mnt/qa-volume qa-bkup-image /usr/sbin/sshd -D'  
+						echo 'Op-3366927u-S3: QA server fails after update and is rolled back'
+						// then use error('aborting') to abort rest of steps
+						
+		                error('aborting')
+	
+						}
+				}
 
 
         			
