Update jen-op-3366927u
S3 start

diff --git a/jen-op-3366927u b/jen-op-3366927u
--- a/jen-op-3366927u
+++ b/jen-op-3366927u
@@ -32,35 +32,41 @@ pipeline {
           }
           stage('Op-3366927u-S2') {
 	          steps {
-// curl test qa svr
+				// curl test qa svr
+				echo 'Op-3366927u-S2: Checking on whether QA server is running after update'				
 				sh 'curl -Is http://localhost:33200|head -n 1 > /tmp/qa-result-file'
 				sh 'cat /tmp/qa-result-file'
-	            echo 'Op-3366927u-S2: Checking on whether QA server is running after update'
+	            
 	          }
           }
           stage('Op-3366927u-S3') {
 	          steps {
-	                 /*
-					 ''' sh '''#!/bin/bash
-	                 ''' puppet resource file /tmp/clone ensure=absent force=true;
-	                 ''' puppet resource file /tmp/clone ensure=directory;
-		             ''' cd /tmp/clone;
-		             ''' git clone https://github.com/hctsky/cdv1c04-devops_repo.git;
-	                 ''' targets=puppetclient1.localdomain;
-	                 ''' locate_script='/tmp/clone/cdv1c04-devops_repo/script_to_run';
-	                 ''' bolt script run $locate_script -t $targets -u clientadm -p user123 --no-host-key-check --run-as root;
-	                 '''
-		    	     */
+				// proceed or rollback
+				v2 = input ( 
+                	message: 'Action',
+                    parameters: [choice(name:'',choices: ['Proceed to Roll out to Prod server', 'Roll back QA server'])]
+					)
+				// if proceed			
+				if (v2 == 'Proceed to Roll out to Prod server'){
+ 					echo 'Op-3366927u-S3: Proceed to roll out to Prod server'
+					}
+				else if (v2 == 'Roll back QA server') {
+					// if rollback, then
+					// execute rollback of qa web svr by using qa-bkup-image
+					// remove qa svr container
+					sh 'docker rm -f 3366927u-qa-svr || true'
+					// run another qa-svr from qa backup image
+					sh 'docker run -d -p 33200:80 --network customnetwork -h 3366927u-qa-svr.localdomain --name 3366927u-qa-svr  --add-host=sddo-vm.localdomain:172.20.113.173 --ip=192.168.100.110 --mount source=qa-volume,target=/mnt/qa-volume qa-bkup-image /usr/sbin/sshd -D'  
+					echo 'Op-3366927u-S3: QA server fails after update and is rolled back'
+					// then use error('aborting') to abort rest of steps
+					
+	                error('aborting')
 
-// proceed or rollback
+					}
 
 
-// if proceed
-        			 echo 'Op-3366927u-S3: Proceed to roll out to Prod server'
-// if rollback, then
-// execute rollback of qa web svr by using qa-bkup-image
-// then use error('aborting') to abort rest of steps
-	                 echo 'Op-3366927u-S3: QA server fails after update and is rolled back'
+        			
+
 	          }
           }
           stage('Op-3366927u-S4') {
